  name: Publish Docker image
on:
  push:
    branches:
      - main
      - master 
    tags:
      - v*
  pull_request:
    branches:
      - main
      - master  

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and Push to Github container registry
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}
          tag_with_ref: true
          username: ${{ secrets.GH_MACHINE_USER_NAME }}
          password: ${{ secrets.GH_MACHINE_USER_TOKEN }}
          cache_froms: ${{ github.repository }}:latest
